### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [vikasdo/Book-Recommendation-Analysis#102]
Hey! I would like to add the following in contributing.md
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on it as a part of GSSOC'21

**Comment by Akshay6890** [comment]
> Hey! I would like to add the following in contributing.md
> 1.Difference between GIT and GITHUB
> 2.How to clone,fork repository
> 3.How to create a branch and then use git push to push to repo
> 4.Create a PR
> 5.Squash commits in a single issue into one
> 6, Updating the forked and local repo as the updations are made in the upstream
> I would like to work on it as a part of GSSOC'21

Ok sure. But after you complete the work you need to put a video showing the work, if everything seems ok then we will accept the PR.

**Comment by khareyash05** [comment]
@Akshay6890 added contributing.md

**Comment by khareyash05** [comment]
![image](https://user-images.githubusercontent.com/60147732/116188386-efef8a80-a744-11eb-8c4f-f8f049076368.png)
![image](https://user-images.githubusercontent.com/60147732/116188412-fa118900-a744-11eb-9c8f-e58571de8ee0.png)
![image](https://user-images.githubusercontent.com/60147732/116188439-04cc1e00-a745-11eb-9dd8-99b32db5c7d1.png)
![image](https://user-images.githubusercontent.com/60147732/116188456-0e558600-a745-11eb-88ba-b3e9b04b8880.png)
@Akshay6890 Will these screenshots work?

**Comment by Akshay6890** [comment]
> ![image](https://user-images.githubusercontent.com/60147732/116188386-efef8a80-a744-11eb-8c4f-f8f049076368.png)
> ![image](https://user-images.githubusercontent.com/60147732/116188412-fa118900-a744-11eb-9c8f-e58571de8ee0.png)
> ![image](https://user-images.githubusercontent.com/60147732/116188439-04cc1e00-a745-11eb-9dd8-99b32db5c7d1.png)
> ![image](https://user-images.githubusercontent.com/60147732/116188456-0e558600-a745-11eb-88ba-b3e9b04b8880.png)
> @Akshay6890 Will these screenshots work?

Cool

**Comment by khareyash05** [comment]
@Akshay6890 Is my PR ready to merge?

**Comment by Akshay6890** [comment]
> @Akshay6890 Is my PR ready to merge?

i didn't check. I will see and accept the PR.
