### ISSUE TITLE
Project Set Up Step by Step 

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#108]
I would like to add a link to a video for Step by step process of setting up this project in local system from forking the repo to running it on server.

**Comment by Akshay6890** [comment]
> I would like to add a link to a video for Step by step process of setting up this project in local system from forking the repo to running it on server.

In README?

**Comment by arpit456jain** [comment]
yes

**Comment by arpit456jain** [comment]
<img width="456" alt="read me" src="https://user-images.githubusercontent.com/55352601/116816948-cc33a680-ab81-11eb-9ff3-b81b8354e577.png">

like this

**Comment by Akshay6890** [comment]
> <img alt="read me" width="456" src="https://user-images.githubusercontent.com/55352601/116816948-cc33a680-ab81-11eb-9ff3-b81b8354e577.png">
> 
> like this

ok

**Comment by Akshay6890** [comment]
> <img alt="read me" width="456" src="https://user-images.githubusercontent.com/55352601/116816948-cc33a680-ab81-11eb-9ff3-b81b8354e577.png">
> 
> like this

Hi, @arpit456jain you working on this?

**Comment by arpit456jain** [comment]
Yes @Akshay6890 will create a PR by end of the day

**Comment by Akshay6890** [comment]
> Yes @Akshay6890 will create a PR by end of the day

Ok.

**Comment by arpit456jain** [comment]
hey @Akshay6890 Is the dark mode added ??
I am not able to see any toggle button and the issue is also closed

**Comment by arpit456jain** [comment]
this is video 
https://drive.google.com/file/d/1iGm91RjynDkhe54Hz8AZTPAM1fMYmEkw/view?usp=sharing

check it once if its ok or not

**Comment by Akshay6890** [comment]
> this is video
> https://drive.google.com/file/d/1iGm91RjynDkhe54Hz8AZTPAM1fMYmEkw/view?usp=sharing
> 
> check it once if its ok or not

Everything looked ok but few changes
1. Change the username from arpit456jain to vikasdo in git clone url
2. make sure to not to encounter any mistakes during setup, as from the video I observed you ran the requirements.txt two times, so that might lead to confusion.

My suggestion would be to make a new video with the above changes in place. I guess it won't be a problem for you.

**Comment by arpit456jain** [comment]
ok will try.
