### ISSUE TITLE
Add Favicon in website.

### ISSUE THREAD

**Issue by RuchiGitHu** [vikasdo/Book-Recommendation-Analysis#117]
### **Feature request**:
I want to add favicon to website so that when a user try to open multiple tabs, they can find that in which tab this website is opened.

### **Describe the solution you'd like**:
Would like to add favicon.

### **Describe how this feature will be useful to our readers**:
when a user try to open multiple tabs, they can find that in which tab this website is opened.

### **Additional context:**
![image](https://user-images.githubusercontent.com/71754179/118017102-d3be3100-b373-11eb-8232-b892c63bd58f.png)
In the first globe tab this website is opened but unable to find it.
<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Akshay6890** [comment]
> ### **Feature request**:
> I want to add favicon to website so that when a user try to open multiple tabs, they can find that in which tab this website is opened.
> 
> ### **Describe the solution you'd like**:
> Would like to add favicon.
> 
> ### **Describe how this feature will be useful to our readers**:
> when a user try to open multiple tabs, they can find that in which tab this website is opened.
> 
> ### **Additional context:**
> ![image](https://user-images.githubusercontent.com/71754179/118017102-d3be3100-b373-11eb-8232-b892c63bd58f.png)
> In the first globe tab this website is opened but unable to find it.
> 
> **Note:**
> 
> * If you want to work on an issue, you should check if it has already been assigned to anyone.

Go ahead, I will assign this to you.
