### ISSUE TITLE
Add more features in admin dashboard

### ISSUE THREAD

**Issue by vikasdo** [vikasdo/Book-Recommendation-Analysis#12]
>show more ways  of user analytics you know

You can view admin URL/admin

**Comment by VishvamPorwal** [comment]
Sir, I would like to work on this issue, its not just about the analytics, there is nothing there in admin.

**Comment by VishvamPorwal** [comment]
but i think this issue coincide with #8 .

**Comment by vikasdo** [comment]
Ok can you add features separately and see previous chats in issue ,
because assigned person hasn't raised any merge request.

**Comment by VishvamPorwal** [comment]
sure i can do that
Now do you just want to use flask-admin or build everything from the ground up.

**Comment by vikasdo** [comment]
can you build from scratch itself.

**Comment by VishvamPorwal** [comment]
sure, I can do that. Please give me some time though.

**Comment by vikasdo** [comment]
take your time, no problem .

**Comment by VishvamPorwal** [comment]
![Screenshot_20210427_141721](https://user-images.githubusercontent.com/59139142/116213308-4d92cf80-a763-11eb-9b14-bff13029d619.png)
I am working on making an admin dashboard like this, there will be more charts, but I want the order date also in the order list table to make this happen, so can i change the schema a little bit and add the date
@vikasdo sir @Akshay6890 sir

**Comment by Akshay6890** [comment]
> ![Screenshot_20210427_141721](https://user-images.githubusercontent.com/59139142/116213308-4d92cf80-a763-11eb-9b14-bff13029d619.png)
> I am working on making an admin dashboard like this, there will be more charts, but I want the order date as well in the order list table to make this happen, so can i change the schema a little bit and add the date
> @vikasdo sir @Akshay6890 sir

yes, go ahead

**Comment by Akshay6890** [comment]
> please assign me this issue @vikasdo

@VishvamPorwal is working on this.
