### ISSUE TITLE
Bug And Enhancements in admin login

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#120]
### **Describe the bug:**

Bug is wrong use of bootstrap alert its not working properly . when i click on cross its not hiding and its not looking good also 
<img width="960" alt="admin2" src="https://user-images.githubusercontent.com/55352601/118249056-9ae0a200-b4c2-11eb-89b5-3f8b86ae1d34.png">

And all labels of username and password is also looking odd because they are in center

**Comment by arpit456jain** [comment]
There is also one more bug , i can submit without entering anything

**Comment by arpit456jain** [comment]
I am working on all these bugs and enhancements under this issue

**Comment by arpit456jain** [comment]
I would like to make a PR for this 

https://user-images.githubusercontent.com/55352601/118250239-df207200-b4c3-11eb-95a1-61cf91c2efa0.mp4

**Comment by arpit456jain** [comment]
@vikasdo @Akshay6890 can I make a PR for this

**Comment by Akshay6890** [comment]
> @vikasdo @Akshay6890 can I make a PR for this

Ok

**Comment by arpit456jain** [comment]
Ok making the PR in 2 mins

**Comment by arpit456jain** [comment]
@Akshay6890 kindly review the PR and add these labels to it

**Comment by Akshay6890** [comment]
> @Akshay6890 kindly review the PR and add these labels to it

sure
