### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#123]
dark mode to website

**Comment by arpit456jain** [comment]
@Akshay6890 can you give me lvl3 for this issue

**Comment by Akshay6890** [comment]
> @Akshay6890 can you give me lvl3 for this issue

Well, the levels are given to PR's based on the issue's importance and the amount of work done, hope you understood.

**Comment by arpit456jain** [comment]
but dark mode is a very big issue . 
adding toggle button then adding js for it then writing css for every page in dark mode . 

I got level3 in every project in which i added this feature and currently i am working on lvl3 issue first then lvl2 and then lvl1

**Comment by Akshay6890** [comment]
> but dark mode is a very big issue .
> adding toggle button then adding js for it then writing css for every page in dark mode .
> 
> I got level3 in every project in which i added this feature and currently i am working on lvl3 issue first then lvl2 and then lvl1

Ok then.
