### ISSUE TITLE
Security feature email alert

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#128]
A email alert to me if someone else is trying to login to my account

**Comment by vikasdo** [comment]
You can work on this issue

**Comment by arpit456jain** [comment]
@vikasdo @Akshay6890 what will be the level

**Comment by Akshay6890** [comment]
> @vikasdo @Akshay6890 what will be the level

level3, of course, because it's a feature of high priority.
