### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by amazingly-abhay** [vikasdo/Book-Recommendation-Analysis#135]
the bookstore link and qr in the readme is not working
![Screenshot from 2024-05-10 00-12-44](https://github.com/vikasdo/Book-Recommendation-Analysis/assets/140364240/bb903e73-a06a-4292-9323-f82f9d791dc6)

**Comment by Akshay6890** [comment]
Hi Abhay, Heroku has stopped hosting projects with free dynos, the reason why you don't see the application.
[Article Link](https://devcenter.heroku.com/changelog-items/2502#:~:text=As%20of%20November%2028th%2C%202022,get%20your%20app%20running%20again.)
And we are currently not actively maintaining this project.
Feel free to fork this and work on this if it helps!

Cheers,
Akshay.
