### ISSUE TITLE
Error Decoding QR ode

### ISSUE THREAD

**Issue by Subhangini** [vikasdo/Book-Recommendation-Analysis#14]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
QR code should work

### Current Behavior

Error Decoding QR code

### Failure Logs

![image](https://user-images.githubusercontent.com/68437435/109538684-66299500-7ae6-11eb-9ca3-953171963e57.png)

**Comment by vikasdo** [comment]
That's a problem then you need to fix open scanner in mobile and get link and try to make it to bar code again in your own way

**Comment by Subhangini** [comment]
From where i can get the link ?

**Comment by vikasdo** [comment]
Scan on mobile or in chrome you have option check it

**Comment by Subhangini** [comment]
The link generate when the QR scans successfully but in this case Qr is not being scanned.

**Comment by Akshay6890** [comment]
> The link generate when the QR scans successfully but in this case Qr is not being scanned.

I see the problem but that's a google generated QR, so there shouldn't be any problem.

**Comment by Subhangini** [comment]
> I see the problem but that's a google generated QR, so there shouldn't be any problem.

Don't know  what's the problem is . Now i think QR is deleted from Readme. :)

**Comment by Akshay6890** [comment]
> > I see the problem but that's a google generated QR, so there shouldn't be any problem.
> 
> Don't know what's the problem is . Now i think QR is deleted from Readme. :)

I will add the QR

**Comment by Subhangini** [comment]
QR code is still not working . should i try creating a new QR for the website?

**Comment by vikasdo** [comment]
Remove QR it works better for me

**Comment by Subhangini** [comment]
> Remove QR it works better for me

Don't know why its not working for me . I tried it using online QR code scanner but its not working .Should I delete the QR from readme

**Comment by Subhangini** [comment]
what I have to do, remove the QR from README or Work on QR??

**Comment by Akshay6890** [comment]
> what I have to do, remove the QR from README or Work on QR??

let the QR be there!
