### ISSUE TITLE
Make a heat map of users for  website

### ISSUE THREAD

**Issue by vikasdo** [vikasdo/Book-Recommendation-Analysis#15]

**Comment by Subhangini** [comment]
I would like to work on this issue. Can I?

**Comment by Anam118** [comment]
@vikasdo Can I work on this issue as i have already added certain heatmaps in my projects.I am a participant of gssoc2021.

**Comment by VishvamPorwal** [comment]
I think we need to first deploy the website to create a heat map, have you already deployed it @vikasdo sir?

**Comment by vikasdo** [comment]
I don't know about it but @John Doe ***@***.***>  has
deployed it please get link from him

**Comment by vikasdo** [comment]
akshay

**Comment by vikasdo** [comment]
https://booklystore.herokuapp.com/login

**Comment by VishvamPorwal** [comment]
I would like to work on this issue but I dont think it would be fair to either anam or shubhangini as they requested to work on this before I did.
