### ISSUE TITLE
Readme updation

### ISSUE THREAD

**Issue by Subhangini** [vikasdo/Book-Recommendation-Analysis#2]
Let me know if this needs to be done
I will try to make it attractive.

**Comment by Aayush-hub** [comment]
@vikasdo Can I work on this?

**Comment by Aayush-hub** [comment]
@vikasdo Can I make PR now or I have to it after 8th March ?

**Comment by vikasdo** [comment]
You can make now no problem

**Comment by vikasdo** [comment]
Please update video link explaining steps and adding text
Link to Video :
https://drive.google.com/file/d/138YFG8sWrRJwtVqcWOFOt8Qin-ZQH7MX/view?usp=drivesdk

**Comment by Aayush-hub** [comment]
@vikasdo Can u provide me resources as the resources already in README file is not working(like link to docs).

**Comment by vikasdo** [comment]
> @vikasdo Can u provide me resources as the resources already in README file is not working(like link to docs) and QR code is not working.

https://drive.google.com/file/d/1f7TCuBrfeaU62j1wUKqRqG286XLAtAC8/view?usp=sharing

**Comment by Aayush-hub** [comment]
@vikasdo Can you please review changes [here](https://github.com/Aayush-hub/Book-Recommendation-Analysis.git) and suggest further changes required if any. And can you provide link of the website as QR code is not working :)

**Comment by vikasdo** [comment]
Remove QR code for now it is under maintenance

**Comment by vikasdo** [comment]
And make a pull request when you have  done changes it is a good practice

**Comment by Aayush-hub** [comment]
@vikasdo Pull request before 8th march is considered for evaluation for GSSoC21?

**Comment by vikasdo** [comment]
Yes, it is we  decide who we can take
