### ISSUE TITLE
Error in Signup

### ISSUE THREAD

**Issue by VishvamPorwal** [vikasdo/Book-Recommendation-Analysis#25]
### Expected Behavior

There should not be an error while signing up, to resolve this in the signup form we have to add two more input fields location and age and insert them in database as well by requesting two more variables from form.

### Current Behavior

When we are signing up there is an error popping up because User table has 5 columns and we are inserting only three of them leaving the other 2 (location and age) empty, hence the error is occurring telling us that we have provided None values.

### Failure Information

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: user.location
[SQL: INSERT INTO user (name, email, password, location, age) VALUES (?, ?, ?, ?, ?)]
[parameters: ('username', 'username@gmail.com', 'sha.........', **None, None**)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

#### Steps to Reproduce

Just try signing up.

I would like to work on this issue @vikasdo sir please assign it to me.
-Thanks

**Comment by VishvamPorwal** [comment]
Also kindly label this issue as GSSOC21 as well.

**Comment by VishvamPorwal** [comment]
@vikasdo sir I have made the necessary changes as told by you and force pushed the repo( .venv files issue ) but 

> vikasdo:main and VishvamPorwal:signup_issue_25 are entirely different commit histories

, this is stopping me from create a pull request in an conventional way it says (https://stackoverflow.com/questions/54750229/remove-virtualenv-files-from-all-previous-commits-after-removing-from-repository) here that you have to force pull it (https://github.com/VishvamPorwal/Book-Recommendation-Analysis.git) in this rep there is a  signup_issue_25 branch in which i have made changes to.

**Comment by VishvamPorwal** [comment]
@vikasdo sir since you fixed this issue and refactored the whole codebase should I delete the previously forked repo and make new pull requests for issue#21 ??

**Comment by vikasdo** [comment]
Yes

**Comment by VishvamPorwal** [comment]
Learned many things from this issue today.
Thank you @vikasdo sir
