### ISSUE TITLE
Add a scroll back to top button

### ISSUE THREAD

**Issue by Debashish-hub** [vikasdo/Book-Recommendation-Analysis#29]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Hello!
I am a GSSOC'21 participant. I would like to add a scroll back to top button in the website.
It would be great if I would be assigned with this issue @vikasdo 
Thank you

**Comment by vikasdo** [comment]
Create a issue and then I will assign
