### ISSUE TITLE
Scroll back to top button

### ISSUE THREAD

**Issue by Debashish-hub** [vikasdo/Book-Recommendation-Analysis#31]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

There will be a scroll back to top button which will take directly to top from button

### Current Behavior

There is no scroll back to top button

#### Steps to Reproduce

A button will be created which will work as scroll back to top

1. step 1
2. step 2
3. you get it...

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* SDK version:
* Toolchain version:

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Akshay6890** [comment]
> ### Prerequisites
> Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**
> 
> * [x]  I am running the latest version
> * [x]  I checked the documentation and found no answer
> * [x]  I checked to make sure that this issue has not already been filed
> 
> ### Expected Behavior
> There will be a scroll back to top button which will take directly to top from button
> 
> ### Current Behavior
> There is no scroll back to top button
> 
> #### Steps to Reproduce
> A button will be created which will work as scroll back to top
> 
> 1. step 1
> 2. step 2
> 3. you get it...
> 
> #### Context
> Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
> 
> * Firmware Version:
> * Operating System:
> * SDK version:
> * Toolchain version:
> 
> ### Failure Logs
> Please include any relevant log snippets or files here.

Hey deabashish, you can just add the scroll top option.

**Comment by arpit456jain** [comment]
@Akshay6890 can i work on this issue ? its been more than 15 days there is no update.

**Comment by Akshay6890** [comment]
> @Akshay6890 can i work on this issue ? its been more than 15 days there is no update.

Will see for 3 more days, and then assign it to you if there's no progress.

**Comment by arpit456jain** [comment]
ok

**Comment by arpit456jain** [comment]
> > @Akshay6890 can i work on this issue ? its been more than 15 days there is no update.
> 
> Will see for 3 more days, and then assign it to you if there's no progress.

@Akshay6890 kindly assign this to me its been 8 days

**Comment by arpit456jain** [comment]
@vikasdo @Akshay6890 kindly review my PR
