### ISSUE TITLE
Make an author dashboard with separate dB for author

### ISSUE THREAD

**Issue by vikasdo** [vikasdo/Book-Recommendation-Analysis#39]
Make author dashboard so author can select their books and ratings

**Comment by VishvamPorwal** [comment]
Sir, I would like to work on this feature, Please assign this issue to me.
Also can you give me some detailed specifications, Is it just viewing ratings of the his books and adding more books that he wrote in the db.

**Comment by vikasdo** [comment]
Author need to know about his book ratings and analysis like top 5 rated books
1. How many user have reviewed it
2. Use books ,users table to find analytics like that
3. Ex : which age user is liking books written by author
4. Their location

**Comment by vikasdo** [comment]
It should give him a complete analysis and you can add the things whatever you wish but it should be a valid one.

**Comment by vikasdo** [comment]
What are the best top 5 reviews positive and negative for an author .

**Comment by VishvamPorwal** [comment]
So sorry for the delay sir, College is eating up every ounce of time I have but I have started working on it.
Also I just wanted to ask if it was ok if I used [canvasjs.com](url) canvasjs's api to plot some relevant graphs.

**Comment by VishvamPorwal** [comment]
One more thing, how will the author be able to access this page should I create a signup route for him as well if yes they how will we link and verify them with the books table. I am open to any advice that you can give me.
Thank you sir

**Comment by VishvamPorwal** [comment]
@Akshay6890 sir please resolve my query as well

**Comment by VishvamPorwal** [comment]
this is an example :
 
https://user-images.githubusercontent.com/59139142/113479853-f3c61f00-94ae-11eb-97f6-7c6f7f7360a7.mp4

@vikasdo sir and @Akshay6890 sir this what I have done up till now 
Now can you tell me 2 things:
1. How will author be able to access this page (I have just putted in name to search)
2. what other features should I add

**Comment by vikasdo** [comment]
you can implement a feture while login ->login as user ,login as author,  and show only book images with title  when he click on them

**Comment by VishvamPorwal** [comment]
how will we verify the login credentials with the authors in books table

**Comment by vikasdo** [comment]
@VishvamPorwal  and add metrics like

1.  what are  TOP 5 rated books?
2. A pie chart of user proportion by age or gender ?

**Comment by vikasdo** [comment]
> how will we verify the login credentials with the authors in books table
> there is no username or password for authors in books table
> nor there is any other author table which is linked to it

yes you can create a separate table and add default password for all of them as of now

**Comment by vikasdo** [comment]
> @VishvamPorwal and add metrics like
> 
> 1. what are  TOP 5 rated books?
> 2. A pie chart of user proportion by age or gender ?]
> 3. and more of metrics on what data available to you and what you can represent

You can see reference of user dashboard of our project

**Comment by VishvamPorwal** [comment]
> > how will we verify the login credentials with the authors in books table
> > there is no username or password for authors in books table
> > nor there is any other author table which is linked to it
> 
> yes you can create a separate table and add default password for all of them as of now

all of them there are literally 100's of entries in books and even if i were to create another table for authors I will still have to connect every entry of books with a foreign key to the author table

**Comment by VishvamPorwal** [comment]
> @VishvamPorwal and add metrics like
> 
> 1. what are  TOP 5 rated books?
> 2. A pie chart of user proportion by age or gender ?]
> 3. and more of metrics on what data available to you and what you can represent

we are not taking gender at the time of signup but I can do everything else for sure

**Comment by vikasdo** [comment]
> > @VishvamPorwal and add metrics like
> > 
> > 1. what are  TOP 5 rated books?
> > 2. A pie chart of user proportion by age or gender ?]
> > 3. and more of metrics on what data available to you and what you can represent
> 
> we are not taking gender at the time of signup but I can do everything else for sure

Gender of user I mean not author

**Comment by vikasdo** [comment]
You can take user who has rated the books of author and segregate the user

**Comment by VishvamPorwal** [comment]
> > > @VishvamPorwal and add metrics like
> > > 
> > > 1. what are  TOP 5 rated books?
> > > 2. A pie chart of user proportion by age or gender ?]
> > > 3. and more of metrics on what data available to you and what you can represent
> > 
> > 
> > we are not taking gender at the time of signup but I can do everything else for sure
> 
> Gender of user I mean not author

![Screenshot_20210403_193516](https://user-images.githubusercontent.com/59139142/113480779-c039c380-94b3-11eb-8a15-572ee5dd840d.png)
Yes I am talking about user as well

**Comment by VishvamPorwal** [comment]
do you want me to add gender as well??

**Comment by VishvamPorwal** [comment]
> do you want me to add gender as well??

In the database I mean at the time of user signup

**Comment by vikasdo** [comment]
> > do you want me to add gender as well??
> 
> In the database I mean at the time of user signup

If you want to show metrics on gender  you can add
