### ISSUE TITLE
Add Description

### ISSUE THREAD

**Issue by Subhangini** [vikasdo/Book-Recommendation-Analysis#4]

**Comment by Subhangini** [comment]
Assign this issue to me

**Comment by Subhangini** [comment]
can i work on this

**Comment by Subhangini** [comment]
![S1](https://user-images.githubusercontent.com/68437435/111737096-fcaad400-88a4-11eb-94de-ec5c92bf17a2.png)
I was talking about this part. This is missing in your repo. I tried to create PR for this but I think this can not be added through a PR. this can only be added by Project Admin.

**Comment by Akshay6890** [comment]
Ok, you can send me the description, I will add it.

**Comment by Subhangini** [comment]
ok

**Comment by Subhangini** [comment]
The E-commerce Industry is rising day by day .So for this we need a Efficient E-commerce Recommendation system . So I this Project We Try to make a recommendation system which will recommend the Items to Authors,Publishers and Retailers in such a way so that they will get a personalized Feed back from user reviews.  Retailer gets more profit By Understanding the customer and focusing on their purchase pattern.

Please edit it if you something feel wrong :)

**Comment by vikasdo** [comment]
added description in about section

**Comment by Subhangini** [comment]
Now you can close this issue :)
