### ISSUE TITLE
Gsoc'21 Bug in Login/Signup System

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#40]
### **Describe the bug:**
There is a very crucial bug in login/Signup system because when i clicked on login without signing up even without entering anything , both field empty I got Login Successful which is very wrong It should give me a message to fill the fields 
I am attaching a video for better understanding my issue.

https://user-images.githubusercontent.com/55352601/111906637-71ce0300-8a77-11eb-841b-59f07141d8ae.mp4

### **To Reproduce:**
4. See an error

### **Expected behavior:**
It should give me required message to fill the fields correctly.
### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by arpit456jain** [comment]
@VamsiMudaliar sir please review it and please add GSSoC'21 label and please assign it to me, i am GSSoC'21 participant

**Comment by Akshay6890** [comment]
> @VamsiMudaliar sir please review it and please add GSSoC'21 label and please assign it to me, i am GSSoC'21 participant

Arpit, go ahead with the working of issue

**Comment by arpit456jain** [comment]
@Akshay6890  Sir I had Solved this issue of form validation may i Create a PR?

**Comment by arpit456jain** [comment]
@Akshay6890 sir Please review my PR #46
