### ISSUE TITLE
Night Mode UI

### ISSUE THREAD

**Issue by ManavArora26** [vikasdo/Book-Recommendation-Analysis#41]
### **Feature request**:
I want to add night mode in the application using toggle switch

### **Is your feature request related to a problem? Please describe. (optional)**:
Helping to reduce eye strain

### **Describe the solution you'd like**:
 I would like to add the toggle switch so the user can switch from light to dark and vice versa

### **Describe alternatives you've considered**:
Rather than toggle switch we can also use toggle bar

### **Describe how this feature will be useful to our readers**:
Less eye strain at night

**Comment by ManavArora26** [comment]
Thank You for assigning me

**Comment by arpit456jain** [comment]
@Akshay6890 are you sure its a level 1 issue?
