### ISSUE TITLE
fix login/ signup issue

### ISSUE THREAD

**Issue by Akshay6890** [vikasdo/Book-Recommendation-Analysis#48]
### **To Reproduce:**
4. See an error

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by arpit456jain** [comment]
Sir please assign it to me

**Comment by arpit456jain** [comment]
sir my code is still present in main code.
<img width="960" alt="p1" src="https://user-images.githubusercontent.com/55352601/112267023-d87f3680-8c9a-11eb-8d36-a0f9a73d4c5b.png">
<img width="960" alt="p2" src="https://user-images.githubusercontent.com/55352601/112267033-da48fa00-8c9a-11eb-8e8c-b380306a74d0.png">

**Comment by arpit456jain** [comment]
I am not able to create a new pull request as there was no change..

**Comment by Akshay6890** [comment]
> I am not able to create a new pull request as there was no change..

try to add comments, in all the files which you changes earlier

**Comment by arpit456jain** [comment]
ok sir. Please assign me this issue

**Comment by arpit456jain** [comment]
Yes sir I had added comments in all three files where i made changes earlier .
Please assign me this issue so i can create a PR.

**Comment by Akshay6890** [comment]
> Yes sir I had added comments in all three files where i made changes earlier .
> Please assign me this issue so i can create a PR.

Done, arpit.

**Comment by arpit456jain** [comment]
thank you sir 
PR has been created please review it and please add labels of gssoc'21
