### ISSUE TITLE
Deploy Website  and Update readme with the link new

### ISSUE THREAD

**Issue by vikasdo** [vikasdo/Book-Recommendation-Analysis#59]
# The website is not working  when it is deployed .

**Comment by Akshay6890** [comment]
> # The website is not working when it is deployed.

don't say it isn't working, you have to specify that, the pickle file doesn't work, and yeah as of now we are using DB.SQLite file to read and write data, we have to make use of a remote SQLite DB.

**Comment by vikasdo** [comment]
Yes you are correct dB.sqlite an python tensorflow,scipy

**Comment by VishvamPorwal** [comment]
Can you refer me a tutorial on how to do so, I am having trouble doing it.

**Comment by vikasdo** [comment]
https://eman-diab5010.medium.com/how-to-deploy-flask-app-on-heroku-step-by-step-38b8044f86f4

**Comment by VishvamPorwal** [comment]
@vikasdo sir I did exactly the same when I deployed the website last time but for some reason database is not being imported on heroku server, also every time I open the website it almost starts from the beginning, doesn't matter if you have already signed up you have to do it again. Same goes with  the books table, all the data of books is somehow unavailable to the server although the names are visible so i guess some of it is there but not all of it.

**Comment by vikasdo** [comment]
@VishvamPorwal  start with basic app and then do our app that's what I told

**Comment by Akshay6890** [comment]
> @vikasdo sir I did exactly the same when I deployed the website last time but for some reason database is not being imported on heroku server, also every time I open the website it almost starts from the beginning, doesn't matter if you have already signed up you have to do it again. Same goes with the books table, all the data of books is somehow unavailable to the server although the names are visible so i guess some of it is there but not all of it.

you can use database plugins provided by heroku
