### ISSUE TITLE
[Gssoc'21] show password button on login and signup

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#66]
### **Feature request**:

I want to add a show password button because its very frustrating to remove whole password if by mistake any wrong key got pressed.

### **Is your feature request related to a problem? Please describe. (optional)**:
A clear and concise description of what the problem is. 

### **Describe how this feature will be useful to our readers**:
A clear and concise description of how this feature will be useful for our  other readers.

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Akshay6890** [comment]
Sorry, this issue has already been already worked on.
