### ISSUE TITLE
[Gssoc'21] Bug in contact Us

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#67]
### **Describe the bug:**
There is s bug in contact us page please watch this video.

https://user-images.githubusercontent.com/55352601/113180497-6b593b80-926e-11eb-86a7-0fc20f3d9f9b.mp4

As you can see any one can overload the server by clicking submitting repetitively.
Also there are no success/error messgage.
### **To Reproduce:**
4. See an error

### **Expected behavior:**
All the fields must be required with some validations

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by arpit456jain** [comment]
@Akshay6890 Kindly assign me this issue .

**Comment by Akshay6890** [comment]
You can work on this and make sure to add a link just like login/ signup for the contact page in header.html file, if you have any trouble in understanding, message me back.

**Comment by arpit456jain** [comment]
@Akshay6890 can you please guide me what's the use of this.
<img width="960" alt="Untitled2" src="https://user-images.githubusercontent.com/55352601/113298749-c6943800-9319-11eb-8c02-b153d93a8bb8.png">
because of this internal server error is occurring. Please check video which will be in next cmnt

**Comment by arpit456jain** [comment]
@Akshay6890 kindly watch this video very care fully Its a very crucial bug that I have just found

https://user-images.githubusercontent.com/55352601/113301149-533ff580-931c-11eb-965f-a5a27a310c74.mp4

**Comment by arpit456jain** [comment]
@Akshay6890 What should i do ?? Can I remove that line if it is not necessary??

**Comment by Akshay6890** [comment]
> @Akshay6890 What should i do ?? Can I remove that line if it is not necessary??

include the following line just below the method declaration
@login_required

**Comment by arpit456jain** [comment]
@Akshay6890 but  that means only logged in members can access contact page.
Don't you think contact us page should be open to all no matter they login or not , just a suggestion.

For now I had added the login required.

**Comment by Akshay6890** [comment]
> @Akshay6890 but that means only logged in members can access contact page.
> Don't you think contact us page should be open to all no matter they login or not , just a suggestion.
> 
> For now I had added the login required.

yes, I referred the same to the participant who worked on this to add it simply in the header page, so that it does not matter whether you are logged in or not, if you want to work on this issue, raise a issue and I will assign you.

**Comment by arpit456jain** [comment]
ok @Akshay6890 let me solve the bug in contact form only in this issue , I am going to create a new issue for this that right now

**Comment by arpit456jain** [comment]
> > @Akshay6890 but that means only logged in members can access contact page.
> > Don't you think contact us page should be open to all no matter they login or not , just a suggestion.
> > For now I had added the login required.
> 
> yes, I referred the same to the participant who worked on this to add it simply in the header page, so that it does not matter whether you are logged in or not, if you want to work on this issue, raise a issue and I will assign you.

@Akshay6890 Kindly review my PR #69  and assign me the new issue #70  for making contact page available for all .
