### ISSUE TITLE
Fields in contact form are not responding to typing.

### ISSUE THREAD

**Issue by Akshay6890** [vikasdo/Book-Recommendation-Analysis#73]
### **Describe the bug:**
Name, email, and phone number fields are not allowing text

### **To Reproduce:**
4. See an error

### **Expected behavior:**
we should be able to type in the text.

### **Screenshots:**
![image](https://user-images.githubusercontent.com/47181903/113547531-b88d3280-960b-11eb-9bac-3f45019ebb1c.png)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.

**Comment by Akshay6890** [comment]
> Can I work on this issue under GSSOC21? Kindly assign it to me.

Sure, why not?

**Comment by Akshay6890** [comment]
> Can I work on this issue under GSSOC21? Kindly assign it to me.

are you working on it? if not we have to assign this to others. Please respond.
