### ISSUE TITLE
Shopping cart bug.

### ISSUE THREAD

**Issue by Akshay6890** [vikasdo/Book-Recommendation-Analysis#74]
### **Describe the bug:**
when you login and browse through the store you see that there is a new item being added to cart which is not visible.

### **Expected behavior:**
if user has any items added in the cart they should stay in the cart until user checks out, the items should also be present in the cart even when user logs in or logs out unless he checks them out.

### **Screenshots:**
![image](https://user-images.githubusercontent.com/47181903/113548074-8cbe7c80-960c-11eb-8fd1-1f096e37f782.png)

This user does not have any items added yet shows there is a item but when you click on it there's nothing in it.
![image](https://user-images.githubusercontent.com/47181903/113548138-a65fc400-960c-11eb-918c-105b5cff2b65.png)

### **Additional context:**
even when you clear cart and click on any book, the invisible item is added again.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by fazer1929** [comment]
I'd like to work on this issue. Shall I go ahead?

**Comment by Akshay6890** [comment]
> I'd like to work on this issue. Shall I go ahead?

Yea, sure.

**Comment by Akshay6890** [comment]
> I'd like to work on this issue. Shall I go ahead?

Hey, fazer are you working on this issue?

**Comment by fazer1929** [comment]
> > I'd like to work on this issue. Shall I go ahead?
> 
> Hey, fazer are you working on this issue?

Hello sorry, got Caught up. I'll do this in 2-3 days for sure.

**Comment by Akshay6890** [comment]
> I'd like to work on this issue. Shall I go ahead?

fazer, any update regarding the work?

**Comment by Supriyo-455** [comment]
@Akshay6890 Hey I want to work on this issue please assign it to me. And also I noticed that when I check out the items from the cart the transaction history remained unchanged and sometimes the details of the items are not visible in the cart.

**Comment by Akshay6890** [comment]
> @Akshay6890 Hey I want to work on this issue please assign it to me. And also I noticed that when I check out the items from the cart the transaction history remained unchanged and sometimes the details of the items are not visible in the cart.

ok

**Comment by Divyanshj** [comment]
I think this issue can be cured by creating cookies.
Please assign me this issue if someone is not working on it

**Comment by raghavasrujan** [comment]
@Akshay6890 Hey I want to work on the issue and already cleared the bug. please assign it to me.

**Comment by Akshay6890** [comment]
> @Akshay6890 Hey I want to work on the issue and already cleared the bug. please assign it to me.

Hi raghavasrujan,I have assigned the task to you, please do a pull request, I would like to verify the code.

**Comment by Akshay6890** [comment]
@raghavasrujan Will review the code a while later as I am occupied with some other tasks.
