### ISSUE TITLE
[Gssoc'21] Making Contact us page more attractive

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#75]
### **Feature request**:
I want to try to make contact page more attractive and cool

**Comment by Akshay6890** [comment]
> ### **Feature request**:
> I want to try to make contact page more attractive and cool

ok

**Comment by arpit456jain** [comment]
<img width="960" alt="whgvi" src="https://user-images.githubusercontent.com/55352601/114036333-9ca0bf80-989d-11eb-8cd1-d49c92219ea8.png">

@Akshay6890 how this??

**Comment by arpit456jain** [comment]
<img width="960" alt="cfklsadnlcvlksbjkvsd" src="https://user-images.githubusercontent.com/55352601/114038185-459bea00-989f-11eb-971c-4678cc6cd725.png">

**Comment by Akshay6890** [comment]
> <img alt="whgvi" width="960" src="https://user-images.githubusercontent.com/55352601/114036333-9ca0bf80-989d-11eb-8cd1-d49c92219ea8.png">
> 
> @Akshay6890 how this??

this looks great, but change the theme color of the button and illustration. Good Job!

**Comment by arpit456jain** [comment]
@Akshay6890 in which color do you want it?

**Comment by arpit456jain** [comment]
<img width="960" alt="kitabe" src="https://user-images.githubusercontent.com/55352601/114051584-d5936100-98aa-11eb-9a97-5d3d233e09d7.png">

**Comment by Akshay6890** [comment]
use previous style and colors only, don't make changes, looks cool.

**Comment by Akshay6890** [comment]
> > <img alt="whgvi" width="960" src="https://user-images.githubusercontent.com/55352601/114036333-9ca0bf80-989d-11eb-8cd1-d49c92219ea8.png">
> > @Akshay6890 how this??
> 
> this looks great, but change the theme color of the button and illustration. Good Job!

finalize this, we will see changes later

**Comment by arpit456jain** [comment]
Ok @Akshay6890 i will create a PR in some time kindly add suitable labels on PR.
As on  last 2 PR s i got level 1 only white there was labels of level 2 on issue 😅

**Comment by arpit456jain** [comment]
@Akshay6890 what happens ?? you close the issue !! why ? the PR is not merged yet!!
