### ISSUE TITLE
[Gssoc'21] Adding a 404 page

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#77]
### **Feature request**:
I want to add a 404 page in the website as it currently look like this.

<img width="950" alt="p11" src="https://user-images.githubusercontent.com/55352601/114062438-260fbc00-98b5-11eb-926b-415f8d877ab2.png">

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/114132757-956fc500-9922-11eb-87d6-98946db90ec2.mp4

how's this ??

**Comment by arpit456jain** [comment]
may I create a PR for this ?

**Comment by vikasdo** [comment]
Ok you can create a PR

**Comment by arpit456jain** [comment]
Ok
