### ISSUE TITLE
Check if email is already registered or not without submitting the form

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#84]
### **Feature request**:

I would like to add a functionality such that it will tell user that this email is already registered while entering email without submitting the form.

### **Is your feature request related to a problem? Please describe. (optional)**:
A clear and concise description of what the problem is. 

### **Describe how this feature will be useful to our readers**:
A clear and concise description of how this feature will be useful for our  other readers.

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Akshay6890** [comment]
> ### **Feature request**:
> I would like to add a functionality such that it will tell user that this email is already registered while entering email without submitting the form.
> 
> ### **Is your feature request related to a problem? Please describe. (optional)**:
> A clear and concise description of what the problem is.
> 
> ### **Describe the solution you'd like**:
> A clear and concise description of what you want to happen.
> 
> ### **Describe alternatives you've considered**:
> A clear and concise description of any alternative solutions or features you've considered.
> 
> ### **Describe how this feature will be useful to our readers**:
> A clear and concise description of how this feature will be useful for our other readers.
> 
> ### **Additional context:**
> Add any other context or screenshots about the feature request here.
> 
> **Note:**
> 
> * If you want to work on an issue, you should check if it has already been assigned to anyone.

Sure.

**Comment by arpit456jain** [comment]
@Akshay6890 kindly review my opened pr
