### ISSUE TITLE
Adding Tech Stack

### ISSUE THREAD

**Issue by JanhaviSoni** [vikasdo/Book-Recommendation-Analysis#85]
### **Feature request**:
Adding tech stack to Readme

### **Is your feature request related to a problem? Please describe. (optional)**:
A clear and concise description of what the problem is. 

### **Describe the solution you'd like**:
Adding techstack section to Readme
Jupyter Notebook/ Google Colab / PySpark

Front End : HTML / CSS / JavaScript

Back End : MongoDB / Flask

Python version 3.0 or Higher

Libraries: sklearn numpy, scipy, matplotlib

### **Describe how this feature will be useful to our readers**:
Users can easily identify the tech stack of their interest and it will help them to contribute easily . Also person who sees the project for the first time tends to go to Readme for whole info so it would help them

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by JanhaviSoni** [comment]
@vikasdo can I work on this issue

**Comment by Akshay6890** [comment]
> @vikasdo can I work on this issue

Hi, @JanhaviSoni any update regarding the work?

**Comment by vikasdo** [comment]
Yes

**Comment by JanhaviSoni** [comment]
@vikasdo  Please check the PR

**Comment by Akshay6890** [comment]
> @vikasdo Please check the PR

You have to open PR in @vikasdo project repository.
