### ISSUE TITLE
Create Dark Mode button

### ISSUE THREAD

**Issue by Akshay6890** [vikasdo/Book-Recommendation-Analysis#96]
### **Feature request**:
Add a button that can toggle between dark and light mode.

### **Describe the solution you'd like**:
Use the common header file, to place the button to avoid any sort of confusion, and when the user first visits the website is in light mode but when the user clicks on the button the theme changes to dark mode. 

### **Describe alternatives you've considered**:
A better user experience would be adding a toggle instead of a button. Just like how GitHub gives used to give us a toggle.

### **Describe how this feature will be useful to our readers**:
Well, the dark mode would be better useful to readers during night time, as this prevents blue light from affecting the eyes of users.

### **Additional context:**
<img style="width:200px; height:200px;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANIAAAC0CAMAAADW6oI3AAAAhFBMVEX///9M7ZJN1YhK5I37+/xIwXzz8/T5+Prv9/Rb65nk9Oz2+/ns6+37/v7U8eGG8bVn1JaJ2ayp8snj4uST8by79tVp6aF36Ki24sqJyaXk6OeU5Ld51qK66tCd2biz6szJ9d2y88/W5t6p5cTK6Nhru45+wZuw2cOW0LCG5rCf7sK/385TjIxTAAADoElEQVR4nO3a2XabMBAGYBix28bgeN+XbG3e//0qgbOYpAnSWKLu+b8rn1xY+T1iJECeBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANDOID+MZ2nqM6TpbDzKB10nqfUmQ0YUIVFFffKHk17XebxszMpDxWqXJzJGL8l3q0Lm8sdZp4ESVoFovUsa37dbkyxV8vVoDgxGrEDll+XIShlq1NFFlUxZgf5aikSGmnZSqD2jw4ki/+6r80Kke0cxPpiYB/JF+UNf65XCn7jJ8Y5zGdHp5+8/kT+yn+IjTo1o02aEDbmt0956oirT3maGSwmnM7SYdbWTSJ31vQGne5ftxynF1NX6xGgNotDYw/UK4ahFJOaJfPp2PWrKyXcz9Rj7Op1pp5RiaCfDJVaRNH/0hHwX+3LG3YRY6Q62EmMbGS71GA2ctH/yjFL794SMfYNY6w+3Fvb3EJzmsNMfbme/QQzME2k3B0U2CNvLbc4oUmEyYCG0ljIDnJ2Ddr9TVuJw7QwNnEup5Rb80sZ6G5+ZR9LbDL3KaXbtDA1OVyUlo+m1MzRwIhktmgml187QYJ7IJ6MBB+RfOUKT80gB+cGVMzT8hxOvg/ZgO5LzJp7RzPLEYyy1NDcZ8ES2l1rOhkjzLr1WipHlKnWwbc0sR2LcXIh/9OaCcTEJk4tpLrd4lqvEulE3mHmFONhO5PUYkUwep4jE/kNk84degrR7XknDwHqVvMw8kgh1H02G1vtdxbhBCEELvaEW9Cuw3h08zhNkWaZ7nZHuHRWJsYOQZQp1XsaE9NtJkTivzPSm3oKmceCgOyjGLzZVmbZtR9mGlMVuAnmM188qU8s9xDykTexo3immewjROpNMdIoczbqaaYtQp+/azD0561ZR7DnNdOBkevzpwM1jXSOXgTzjY1HVKcnw+/XpPgxpHsWuExkfXjtnWvz98NoiDItjpJqd80yGRwzPmcLF10cMZSDaLlUi91XyTA+C1id0ZaiHp+ZB0PmD/PP62I+crbGfGR3XFW+hwofnp2PW8wZJdpw/qzy0fln2I5cL0mdGh6pfj1KHDcX2KAN1WaOz6uj7VKsDvp8Pr7MQFevty92dCqTidB1Jn5xXcRBF/f5yefdmueyrCqnmfXOBqu4s51YcRyrWq6jOc5OBFPWPq1BVrIr6XOW50URKnSqog1UfbjuPUgWoltTgHPDWE1UuYgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1x+hOS0kldD1IgAAAABJRU5ErkJggg=="/>

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by mehak6569** [comment]
Sir,
I want to work on this issue. Please assign it to me.

**Comment by Akshay6890** [comment]
> Sir,
> I want to work on this issue. Please assign it to me.

Done. But make sure to use a common header file for placing the toggle.

**Comment by mehak6569** [comment]
> > Sir,
> > I want to work on this issue. Please assign it to me.
> 
> Done. But make sure to use a common header file for placing the toggle.

Will keep that in mind.
Thank you!

**Comment by chazuttu** [comment]
I am GSSOC'21 Participant. I added a PR for this issue,thanks for merging it.
